language: python
python:
 - 3.9
 - nightly
services:
 - postgresql
install:
 - cd services/auth/
 - pip install pipenv
 - pipenv install pytest
 - pipenv install
before_script:
 - psql -c "CREATE DATABASE firmus_test;" -U postgres
script: 
 - python -m pytest tests/unit/
 - python -m pytest tests/integration/
 - python -m pytest tests/system/services/test_category.py
 - python -m pytest tests/system/services/test_job.py