language: python
python:
 - "3.9"
 - "nightly"
services:
 - postgresql
install:
 - cd services/auth/
 - "pip install pipenv"
 - "pipenv install pytest"
 - "pipenv install"
script: python -m pytest tests/